language: node_js
node_js:
- '7'
sudo: required
cache:
  npm: true
  directories:
    - /home/travis/.cache/Cypress
    - ~/.npm
script:
- npm i -g ngrok --unsafe-perm=true --allow-root
- npm install -g grunt-cli
- mkdir public
- curl -sO http://stedolan.github.io/jq/download/linux64/jq
- chmod +x jq
- ngrok http file://$(pwd)/public/ --authtoken=$NGROK_AUTH_TOKEN > /dev/null &
- sleep 3
- echo {} > credentials.json
- grunt zip
- NGROK_PATH=$(curl 'http://localhost:4040/api/tunnels' | ./jq -r '.tunnels[0].public_url')/theme.zip
- echo "{\"theme\":{\"name\":\"GitlabCI Curl Test - $(date +"%D %T %Z")\",\"src\":\"$NGROK_PATH\"}}" > body.json
- echo $(cat body.json)
- 'TEST_THEME_ID=$(curl -d @body.json -H "Accept: application/json" -H "Content-Type: application/json" https://$SHOPIFY_API_KEY:$SHOPIFY_API_PASSWORD@$SHOPIFY_URL/admin/api/2019-04/themes.json | ./jq -r ''.theme.id'')'
- if [ ${TEST_THEME_ID} == null ] ; then exit 1 ; fi
- while [ $(curl https://$SHOPIFY_API_KEY:$SHOPIFY_API_PASSWORD@$SHOPIFY_URL/admin/api/2019-04/themes/$TEST_THEME_ID.json | ./jq -r '.theme.previewable') != 'true' ]; do echo 'Waiting for theme'; sleep 2; done
- $(npm bin)/cypress run --env SHOPIFY_URL=$SHOPIFY_URL,SHOPIFY_THEME_ID=$TEST_THEME_ID
- 'curl -H "Accept: application/json" -X DELETE https://$SHOPIFY_API_KEY:$SHOPIFY_API_PASSWORD@$SHOPIFY_URL/admin/api/2019-04/themes/$TEST_THEME_ID.json'
addons:
  chrome: stable
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
# env:
#   global:
#   - SHOPIFY_URL: integration-testing-example.myshopify.com
